# Generated by Django 4.2.16 on 2026-05-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.SlugField(help_text='Groups this item for a website section, for example about_values or resource_items.')),
                ('eyebrow', models.CharField(blank=True, help_text='Optional small label shown above the title, such as Focus Area or Gender Equality.', max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Optional Material Symbols icon name.', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('static_path', models.CharField(blank=True, help_text='Optional static image path, for bundled launch/gallery images.', max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
