# Generated by Django 4.2.16 on 2026-05-20 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contentlistitem_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, help_text='Leave blank to generate automatically from the title.', unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on the blog listing page.')),
                ('body', models.TextField(help_text='Main blog content. Paragraph breaks are preserved.')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('author_name', models.CharField(default='IPADEV', max_length=120)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
