# Generated by Django 4.2.16 on 2026-05-20 10:31

import datetime

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def seed_nawoj_blog_post(apps, schema_editor):
    BlogPost = apps.get_model("pages", "BlogPost")
    BlogPostImage = apps.get_model("pages", "BlogPostImage")

    body = """On Tuesday, May 19, 2026, the Nigeria Association of Women Journalists (NAWOJ), Ekiti State Chapter, hosted a timely and important public lecture in Ado-Ekiti focused on one of the most urgent democratic conversations in Nigeria today - women's political representation.

The lecture, delivered by the Founder of Inclusive Pathway Development Initiative (IPADEV), Dr. Margaret Fagboyo, was titled:

"Understanding the Special Seats Bill: Women's Representation in Nigerian Politics, Current Statistics and Challenges - Lessons from Rwanda, Uganda and Kenya on Women's Political Representation."

The event brought together government officials, gender advocates, journalists, civil society actors, and community leaders to discuss the growing push for the passage of the Special Seats Bill (HB 1349), a constitutional amendment bill seeking to create additional legislative seats for women in Nigeria's National and State Houses of Assembly.

For many people, the conversation around women's representation is often misunderstood as a "women's issue." But the reality is much bigger than that. Representation is fundamentally about democracy, fairness, and ensuring that decision-making spaces reflect the diversity and experiences of the people they govern.

Nigeria remains one of the countries with the lowest female political representation globally. Women constitute nearly half of the country's population, yet their presence in legislative spaces remains abysmally low. According to discussions at the lecture, women occupy less than 5% of seats in many legislative institutions across the country.

Dr. Fagboyo explained that the proposed Special Seats Bill is not designed to stop women from contesting existing political offices. Rather, it is intended as a temporary corrective constitutional measure to address long-standing structural barriers that have historically excluded women from governance and political participation.

The lecture also examined lessons from countries such as Rwanda, Uganda, Kenya, Senegal, and South Africa, where constitutional reforms, reserved seats, and gender quotas have significantly improved women's representation in governance. Rwanda, for example, currently has one of the highest percentages of women in parliament globally - a development largely driven by deliberate constitutional and policy reforms.

One important point repeatedly emphasized during the lecture was that inclusive governance produces better outcomes. When women participate meaningfully in governance, policies around healthcare, education, social welfare, child protection, peacebuilding, and community development often receive stronger attention.

Dr. Fagboyo also highlighted the barriers that continue to discourage women from active political participation in Nigeria. These include political violence, financial exclusion, cultural stereotypes, intimidation, weak institutional support, and poor media representation of women in leadership.

Beyond the lecture itself, the event also served as recognition of years of advocacy and community impact. One of the highlights of the programme was the presentation of an award to Dr. Margaret Fagboyo in recognition of her contributions to women development initiatives and advocacy against gender-based violence.

At IPADEV, we strongly believe that inclusive governance is not charity. It is good governance. A democracy cannot be truly representative when half of its population remains largely excluded from decision-making spaces.

The conversation must continue. The advocacy must continue. And more importantly, the political will to act must emerge.

Nigeria cannot build an inclusive future while leaving women behind."""

    post, _ = BlogPost.objects.update_or_create(
        slug="nawoj-public-lecture-womens-political-representation",
        defaults={
            "title": "NAWOJ Public Lecture: Why Nigeria Must Take Women's Political Representation Seriously",
            "excerpt": (
                "Dr. Margaret Fagboyo delivered a public lecture in Ado-Ekiti on the "
                "Special Seats Bill, women's political representation, and the need "
                "for inclusive governance in Nigeria."
            ),
            "body": body,
            "featured_image_static_path": "img/blog/nawoj-public-lecture/public-lecture-audience-wide.jpeg",
            "author_name": "IPADEV",
            "published_at": timezone.make_aware(datetime.datetime(2026, 5, 19, 9, 0)),
            "status": "published",
        },
    )

    BlogPostImage.objects.filter(post=post).delete()
    images = [
        (
            "img/blog/nawoj-public-lecture/award-presentation.jpeg",
            "Dr. Margaret Fagboyo receives recognition for her advocacy and community impact.",
            "Award presentation at the NAWOJ public lecture",
        ),
        (
            "img/blog/nawoj-public-lecture/public-lecture-audience-wide.jpeg",
            "Participants listen during the public lecture on women's political representation.",
            "Audience at the NAWOJ public lecture in Ado-Ekiti",
        ),
        (
            "img/blog/nawoj-public-lecture/dr-fagboyo-speaking.jpeg",
            "Dr. Margaret Fagboyo speaks on the Special Seats Bill and inclusive governance.",
            "Dr. Margaret Fagboyo speaking at the public lecture",
        ),
        (
            "img/blog/nawoj-public-lecture/nawoj-group-photo.jpeg",
            "NAWOJ members, advocates, and guests at the public lecture.",
            "Group photograph with NAWOJ members and guests",
        ),
        (
            "img/blog/nawoj-public-lecture/student-group-photo.jpeg",
            "Students and young participants join the conversation on inclusive governance.",
            "Students and young participants at the event",
        ),
        (
            "img/blog/nawoj-public-lecture/award-recognition-group.jpeg",
            "Women leaders and advocates celebrate the recognition presented to Dr. Fagboyo.",
            "Women leaders and advocates with Dr. Margaret Fagboyo",
        ),
        (
            "img/blog/nawoj-public-lecture/audience-engagement.jpeg",
            "Dr. Fagboyo engages participants during the lecture.",
            "Audience engagement during the NAWOJ public lecture",
        ),
    ]
    BlogPostImage.objects.bulk_create(
        [
            BlogPostImage(
                post=post,
                static_path=static_path,
                caption=caption,
                alt_text=alt_text,
                sort_order=index,
            )
            for index, (static_path, caption, alt_text) in enumerate(images, start=1)
        ]
    )


def remove_nawoj_blog_post(apps, schema_editor):
    BlogPost = apps.get_model("pages", "BlogPost")
    BlogPost.objects.filter(slug="nawoj-public-lecture-womens-political-representation").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_static_path',
            field=models.CharField(blank=True, help_text='Optional static image path for bundled blog images.', max_length=220),
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(blank=True, upload_to='blog/gallery/')),
                ('static_path', models.CharField(blank=True, help_text='Optional static image path for bundled blog gallery images.', max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='pages.blogpost')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_nawoj_blog_post, remove_nawoj_blog_post),
    ]
